phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 508955320023.dkr.ecr.$AWS_REGION.amazonaws.com
